apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.admin: apiKey, login
  accounts.admin.enabled: "true"