apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: myapp
  annotations: 
   argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo
   argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80